config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  
  devise_for :users
  
  get 'portifolio', to: 'users#portifolio'
  get 'friends', to: 'users#friends'
  get 'search_friend', to: 'users#search'
  resources :users, only: [:show]
  
  get 'search_stock', to: 'stocks#search'
  
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, presence: true
  validates :ticker, presence: true
  
  # Class method to lookup a stock price
  def self.new_lookup(ticker)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_api[:publishable_token],
      secret_token: Rails.application.credentials.iex_api[:secret_token],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    
    begin      
      # The code bellow is equal to the above it
      # Stock.new(ticker: ticker, name: client.company(ticker).company_name, last_price: client.price(ticker))
      new(ticker: ticker.upcase, name: client.company(ticker).company_name, last_price: client.price(ticker))
    rescue => exception
      return nil
    end
  end

  # Class method to lookup a for an existing stock ticker
  def self.check_db(ticker)
    # The code bellow is equal to the above it
    # Stock.where(ticker: ticker).first
    where(ticker: ticker).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = first_name_matches(param) + last_name_matches(param) + email_matches(param)
    to_send_back.uniq!

    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end
  
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |u| u.id == self.id }
  end

  def follows?(friend)
    friendships.where(friend_id: friend.id).exists?
  end

  def can_track_stock?(ticker)
    under_stock_limit? && !stock_already_tracked?(ticker)
  end
  
  def stock_already_tracked?(ticker)
    stock = Stock.check_db(ticker)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create   
    friend = User.find(params[:friend])
    @user_friend = Friendship.create(user: current_user, friend: friend)

    flash[:notice] = "User #{friend.full_name} was added as your friend"
    redirect_to friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    if friendship.destroy
      flash[:notice] = "User was successfully removed as your friend"
      redirect_to friends_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        # render json: @stock
        # render 'users/portifolio'
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid stock ticker"
          format.js { render partial: 'users/result' }
          format.html { redirect_to portifolio_path }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a valid stock ticker"
        format.js { render partial: 'users/result' }
        format.html { redirect_to portifolio_path }
      end
    end
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)

    flash[:notice] = "Stock #{stock.name} was successfully added to your portifolio"
    redirect_to portifolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    if user_stock.destroy
      flash[:notice] = "Stock #{stock.name} was successfully removed from your portifolio"
      redirect_to portifolio_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def portifolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end
  
  def friends
    @friends = current_user.friends
  end  
  
  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Friend not found"
          format.js { render partial: 'users/friend_result' }
          format.html { redirect_to friends_path }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a valid name or email"
        format.js { render partial: 'users/friend_result' }
          format.html { redirect_to friends_path }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |f| %>
        <tr>
          <th scope="row"><%= f.email %></th>
          <td><%= f.first_name %></td>
          <td><%= f.last_name %></td>
          <td><%= link_to 'Stop following', friendship_path(f), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-sm btn-warning"%> | 
            <%= link_to 'View Profile', f, class: "btn btn-sm btn-success"%>
          </td>
        </tr>        
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible fade show">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-danger alert-dismissible fade show">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <%= alert %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'FinanceTrackerBR', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <% if current_user %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if request.path == portifolio_path %>">
          <%= link_to 'My Portifolio', portifolio_path, class: "nav-link" %>          
        </li>
        <li class="nav-item <%= 'active' if request.path == friends_path %>">
          <%= link_to 'My Friends', friends_path, class: "nav-link" %>          
        </li>        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <%= fa_icon 'edit' %> Edit
            <% end %>
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>        
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item user-name">
          <%= fa_icon 'user' %> <%= current_user.full_name %>
        </li>
        <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-danger logout-btn" %></li>
      </ul>
    </div>
  </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to Finance Tracker BR</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |s| %>
        <tr>
          <th scope="row"><%= s.ticker %></th>
          <td><%= s.name %></td>
          <td><%= s.last_price %></td>
          <td>
          <% if current_user.id == @user.id %>
          <%= link_to 'Remove', user_stock_path(s), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-sm btn-warning"%>
          <% end %>
          </td>
        </tr>        
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<% if @friends %>
<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <% @friends.each do |f| %>
        <tr>
          <td><strong>Email:</strong> <%= f.email %></td>
          <td><strong>Name:</strong> <%= f.full_name %></td>
          <td><strong>Actions:</strong> <%= link_to 'View Profile', f, class: "btn btn-sm btn-success" %>
          <% if !current_user.follows?(f) %>
          <%= link_to 'Follow friend?', friendships_path(friend: f), method: :post, class: 'btn btn-sm btn-success' %>
          <% else %>
          <span class="badge badge-secondary">
            You're already following this user    
          </span>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = "<%= escape_javascript(render 'users/friend_result.html') %>";

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<% if @stock %>
<div class="card card-header results-block">
  <strong>Symbol:</strong> <%= @stock.ticker %>
  <strong>Name:</strong> <%= @stock.name %>
  <strong>Price:</strong> <%= @stock.last_price %>
  <% if current_user.can_track_stock?(@stock.ticker) %>
  <%= link_to 'Add to my portifolio', user_stocks_path(user:current_user, ticker: @stock.ticker), method: :post, class: 'btn btn-success' %>
  <% else %>
  <span class="badge badge-secondary">
    You're already tracking
    <%= " 10 stocks" if !current_user.under_stock_limit? %>
    <%= " this stock" if current_user.stock_already_tracked?(@stock.ticker) %>
  </span>
  <% end %>
</div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = "<%= escape_javascript(render 'users/result.html') %>";

app/views/users/friends.html.erb
<h1>My Friends</h1>

<div class="search-area">
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: 'Enter a name or email to search', autofocus: true, class: 'form-control form-control-lg' %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <%= fa_icon 'search 2x'%>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="friend-results"></div>

<% if !@friends.empty? %>
<%= render 'friendships/list' %>
<% end %>

app/views/users/portifolio.html.erb
<h1>My Portifolio</h1>

<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: 'Stock ticker symbol', autofocus: true, class: 'form-control form-control-lg' %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <%= fa_icon 'search 2x'%>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="results"></div>

<% if !@tracked_stocks.empty? %>
<%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Email:</strong> <%= @user.email %></td>
        <td><strong>Name:</strong> <%= @user.full_name %></td>
        <td><strong>Actions:</strong> 
        <% if !current_user.follows?(@user) %>
        <%= link_to 'Follow friend?', friendships_path(friend: @user), method: :post, class: 'btn btn-sm btn-success' %>
        <% else %>
        <span class="badge badge-secondary">
          You're already following this user    
        </span>
        <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
<%= render 'stocks/list' %>
<% end %>